trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'html'
    publishLocation: 'Container'
  displayName: 'Publish Artifact'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(9c49e2f3-8629-43cc-bec5-c1cea9abb8a2)'
    appType: 'webAppLinux'
    WebAppName: 'happy-birthday-priyanka'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'