# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Pay-As-You-Go(9c49e2f3-8629-43cc-bec5-c1cea9abb8a2)'
    appType: 'webAppLinux'
    WebAppName: 'happy-birthday-priyanka'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
